AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  PutItems:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 12
      Role: 'arn:aws:iam::661588767260:role/service-role/PutItemsRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /items
            Method: PUT
