AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    LambdaFunction:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: ""
            FunctionName: "get_detail_of_single_application"
            Handler: "lambda_function.lambda_handler"
            Architectures: 
              - "x86_64"
            Code: 
                S3Bucket: "prod-04-2014-tasks"
                S3Key: !Sub "/snapshots/${AWS::AccountId}/get_detail_of_single_application-ba681a13-a93c-4621-95e9-892771501ddf"
                S3ObjectVersion: "4FEZx5SM_NjNcqe5tTwaE6GCCwOhGsjg"
            MemorySize: 128
            Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/AllowLambdaDynamoDb"
            Runtime: "python3.9"
            Timeout: 3
            TracingConfig: 
                Mode: "PassThrough"

