AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'QMS : to put/update queries of specific user to their pool'
Resources:
  putquery:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: 'QMS : to put/update queries of specific user to their pool'
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::661588767260:role/service-role/PutItemsRole'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /studentqueries
            Method: PUT
