AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Applications : put meta deta of application'
Resources:
  PutSingleAplicationDetails:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: 'Applications : put meta deta of application'
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::661588767260:role/AllowLambdaDynamoDb'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /applications
            Method: POST
