AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: This function handles all submission of an application.
Resources:
  SubmitApplications:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: This function handles all submission of an application.
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::661588767260:role/AllowLambdaDynamoDb'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /SubmitApplications
            Method: PUT
        Api2:
          Type: Api
          Properties:
            Path: /SubmitApplications
            Method: ANY
